# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PingpongChampionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pingpong_championship',
                'verbose_name': 'ChampionShip',
                'verbose_name_plural': 'ChampionShips',
            },
        ),
        migrations.CreateModel(
            name='PingpongChampionshipPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongChampionship')),
            ],
            options={
                'db_table': 'pingpong_championship_player',
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='PingpongPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=32)),
                ('defence_length', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pingpong_player',
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='PingpongReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongChampionship')),
            ],
            options={
                'db_table': 'pingpong_referee',
                'verbose_name': 'Referee',
                'verbose_name_plural': 'Referee',
            },
        ),
        migrations.CreateModel(
            name='PingpongRefereeGameDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_play', models.IntegerField()),
                ('round', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongChampionship')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponent', to='pingpong.PingpongPlayer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to='pingpong.PingpongPlayer')),
            ],
            options={
                'db_table': 'pingpong_referee_game_draw',
                'verbose_name': 'Game Draw',
                'verbose_name_plural': 'Game Draw',
            },
        ),
        migrations.CreateModel(
            name='PingpongRefereeGameTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.IntegerField()),
                ('suggested_numbers', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongChampionship')),
                ('defending_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='defending', to='pingpong.PingpongPlayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongRefereeGameDraw')),
                ('offending_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offending', to='pingpong.PingpongPlayer')),
            ],
            options={
                'db_table': 'pingpong_referee_game_transaction',
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='PingpongRefereeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongChampionship')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongRefereeGameDraw')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongPlayer')),
            ],
            options={
                'db_table': 'pingpong_referee_score',
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.AddField(
            model_name='pingpongchampionshipplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pingpong.PingpongPlayer'),
        ),
    ]
